// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function ReadConfig():Promise<service.Config>;

export function ReceiveConfigUpdate(arg1:Record<string, any>):Promise<void>;

export function SaveConfig():Promise<void>;

export function StartupPrepare(arg1:string):Promise<void>;
