// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadConfig() {
  return window['go']['service']['Config']['ReadConfig']();
}

export function ReceiveConfigUpdate(arg1) {
  return window['go']['service']['Config']['ReceiveConfigUpdate'](arg1);
}

export function SaveConfig() {
  return window['go']['service']['Config']['SaveConfig']();
}

export function StartupPrepare(arg1) {
  return window['go']['service']['Config']['StartupPrepare'](arg1);
}
