// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAddr() {
  return window['go']['service']['DIContainer']['GetAddr']();
}

export function GetAppCtx() {
  return window['go']['service']['DIContainer']['GetAppCtx']();
}

export function GetFileHandler() {
  return window['go']['service']['DIContainer']['GetFileHandler']();
}

export function GetHttpServer() {
  return window['go']['service']['DIContainer']['GetHttpServer']();
}

export function GetImgPath() {
  return window['go']['service']['DIContainer']['GetImgPath']();
}

export function GetLocale() {
  return window['go']['service']['DIContainer']['GetLocale']();
}

export function GetResourcePath() {
  return window['go']['service']['DIContainer']['GetResourcePath']();
}

export function ListIndependencies() {
  return window['go']['service']['DIContainer']['ListIndependencies']();
}

export function Register(arg1, arg2) {
  return window['go']['service']['DIContainer']['Register'](arg1, arg2);
}

export function SetAddr(arg1) {
  return window['go']['service']['DIContainer']['SetAddr'](arg1);
}

export function SetAppCtx(arg1) {
  return window['go']['service']['DIContainer']['SetAppCtx'](arg1);
}

export function SetAssetsPath() {
  return window['go']['service']['DIContainer']['SetAssetsPath']();
}

export function SetLocale(arg1) {
  return window['go']['service']['DIContainer']['SetLocale'](arg1);
}
