// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {service} from '../models';
import {model} from '../models';

export function GetAddr():Promise<string>;

export function GetAppCtx():Promise<context.Context>;

export function GetFileHandler():Promise<service.FileHandler>;

export function GetHttpServer():Promise<service.HttpServer>;

export function GetImgPath():Promise<Record<string, string>>;

export function GetResourcePath():Promise<model.ResourcePath>;

export function ListIndependencies():Promise<Record<string, any>>;

export function Register(arg1:string,arg2:any):Promise<void>;

export function Resolve(arg1:string):Promise<any|boolean>;

export function SetAddr(arg1:string):Promise<void>;

export function SetAppCtx(arg1:context.Context):Promise<void>;

export function SetAssetsPath():Promise<void>;
