// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnsureDir(arg1:string):Promise<void>;

export function Exists(arg1:string):Promise<boolean>;

export function GetRourcePath():Promise<Record<string, string>>;

export function JoinPaths(arg1:Array<string>):Promise<string>;

export function ReadFile():Promise<void>;

export function ReadFileById():Promise<void>;
