// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnsureDir(arg1) {
  return window['go']['service']['FileHandler']['EnsureDir'](arg1);
}

export function Exists(arg1) {
  return window['go']['service']['FileHandler']['Exists'](arg1);
}

export function GetRourcePath() {
  return window['go']['service']['FileHandler']['GetRourcePath']();
}

export function JoinPaths(arg1) {
  return window['go']['service']['FileHandler']['JoinPaths'](arg1);
}

export function ReadFile() {
  return window['go']['service']['FileHandler']['ReadFile']();
}

export function ReadFileById() {
  return window['go']['service']['FileHandler']['ReadFileById']();
}
