// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function EnsureDir(arg1:string):Promise<void>;

export function ListDir(arg1:string):Promise<Record<string, Array<string>>>;

export function PathJoin(arg1:Array<string>):Promise<string>;

export function QueryByName(arg1:string):Promise<Array<model.ItemRaw>>;

export function ReadDynamicStrings():Promise<Record<string, any>>;

export function ReadFile(arg1:string):Promise<Record<string, any>|boolean>;

export function ReadFileById(arg1:string):Promise<model.ItemInfo>;

export function ReadLocales():Promise<Record<string, any>>;
