// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnsureDir(arg1) {
  return window['go']['service']['FileHandler']['EnsureDir'](arg1);
}

export function GetExePath() {
  return window['go']['service']['FileHandler']['GetExePath']();
}

export function ListDir(arg1) {
  return window['go']['service']['FileHandler']['ListDir'](arg1);
}

export function PathJoin(arg1) {
  return window['go']['service']['FileHandler']['PathJoin'](arg1);
}

export function QueryByName(arg1) {
  return window['go']['service']['FileHandler']['QueryByName'](arg1);
}

export function ReadDynamicStrings() {
  return window['go']['service']['FileHandler']['ReadDynamicStrings']();
}

export function ReadFile(arg1) {
  return window['go']['service']['FileHandler']['ReadFile'](arg1);
}

export function ReadFileById(arg1) {
  return window['go']['service']['FileHandler']['ReadFileById'](arg1);
}

export function ReadLocales() {
  return window['go']['service']['FileHandler']['ReadLocales']();
}
