// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateSearchIndex(arg1:any,arg2:string):Promise<void>;

export function ListDifferentLangXml(arg1:string,arg2:string):Promise<Record<string, Array<string>>>;

export function NormalizeWhitespace(arg1:string):Promise<string>;

export function OpenFolderDialog():Promise<Record<string, string>>;

export function StripDataPlaceholders(arg1:string):Promise<string>;

export function XmlToJson(arg1:string,arg2:string):Promise<Record<string, string>>;
