// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateSearchIndex(arg1, arg2) {
  return window['go']['service']['GameData']['GenerateSearchIndex'](arg1, arg2);
}

export function ListDifferentLangXml(arg1, arg2) {
  return window['go']['service']['GameData']['ListDifferentLangXml'](arg1, arg2);
}

export function NormalizeWhitespace(arg1) {
  return window['go']['service']['GameData']['NormalizeWhitespace'](arg1);
}

export function OpenFolderDialog() {
  return window['go']['service']['GameData']['OpenFolderDialog']();
}

export function StripDataPlaceholders(arg1) {
  return window['go']['service']['GameData']['StripDataPlaceholders'](arg1);
}

export function XmlToJson(arg1, arg2) {
  return window['go']['service']['GameData']['XmlToJson'](arg1, arg2);
}
