// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AppCheckForUpdates():Promise<model.ResponseMsg>;

export function DownloadUpdates():Promise<model.ResponseMsg>;

export function HasLatestVersion(arg1:string,arg2:string):Promise<void>;

export function StartUpdate():Promise<void>;
