// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppCheckForUpdates() {
  return window['go']['service']['Updater']['AppCheckForUpdates']();
}

export function DownloadUpdates() {
  return window['go']['service']['Updater']['DownloadUpdates']();
}

export function HasLatestVersion(arg1, arg2) {
  return window['go']['service']['Updater']['HasLatestVersion'](arg1, arg2);
}

export function StartUpdate() {
  return window['go']['service']['Updater']['StartUpdate']();
}
