// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates(arg1) {
  return window['go']['service']['Updater']['CheckForUpdates'](arg1);
}

export function DownloadUpdates() {
  return window['go']['service']['Updater']['DownloadUpdates']();
}

export function StartUpdate() {
  return window['go']['service']['Updater']['StartUpdate']();
}
