// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates(arg1:string):Promise<Record<string, any>>;

export function DownloadUpdates():Promise<Record<string, any>>;

export function StartUpdate():Promise<void>;
