// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsWindowFullscreen() {
  return window['go']['service']['Window']['IsWindowFullscreen']();
}

export function WindowFullscreen() {
  return window['go']['service']['Window']['WindowFullscreen']();
}

export function WindowGetPosition() {
  return window['go']['service']['Window']['WindowGetPosition']();
}

export function WindowGetSize() {
  return window['go']['service']['Window']['WindowGetSize']();
}

export function WindowMinimise() {
  return window['go']['service']['Window']['WindowMinimise']();
}

export function WindowSetAlwaysOnTop(arg1) {
  return window['go']['service']['Window']['WindowSetAlwaysOnTop'](arg1);
}

export function WindowSetSize(arg1, arg2) {
  return window['go']['service']['Window']['WindowSetSize'](arg1, arg2);
}

export function WindowUnfullscreen() {
  return window['go']['service']['Window']['WindowUnfullscreen']();
}

export function WindwoClose() {
  return window['go']['service']['Window']['WindwoClose']();
}
