// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsWindowFullscreen():Promise<boolean>;

export function WindowFullscreen():Promise<void>;

export function WindowGetPosition():Promise<Record<string, number>>;

export function WindowGetSize():Promise<Record<string, number>>;

export function WindowMinimise():Promise<void>;

export function WindowSetAlwaysOnTop(arg1:boolean):Promise<void>;

export function WindowSetSize(arg1:number,arg2:number):Promise<void>;

export function WindowUnfullscreen():Promise<void>;

export function WindwoClose():Promise<void>;
