// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPlatform() {
  return window['go']['main']['App']['CheckPlatform']();
}

export function UpdateApp() {
  return window['go']['main']['App']['UpdateApp']();
}
