// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPlatform():Promise<void>;

export function UpdateApp():Promise<Record<string, any>>;
